version: '3.8'

volumes:
  url-cassandra:
  my-app:
services:
  cassandra: 
    image: cassandra:4.1
    container_name: cassandraDb
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: 'Cluster'
      CASSANDRA_DC: "DC1"
      CASSANDRA_RACK: "RAC1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    volumes:
      - url-cassandra:/var/lib/cassandra  
    
  my-app:
    build:
      context: .
      dockerfile: src/UrlShortener.API/Dockerfile
    container_name: urlshortener-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - cassandra
    restart: unless-stopped